models/Mahasiswa.php
<?php  
namespace app\models;

use yii\db\ActiveRecord;

/**
 * 
 */
class Mahasiswa extends ActiveRecord
{
	
	public static function tableName()
	{
		# code...
		return 'mahasiswa';
	}

	public function rules()
	{
		# code...
		return[
			[['nim','nama','jekel','id_prodi','email','alamat'], 'required'],
			[['nim','nama','jekel','alamat'], 'string'],
			[['email'], 'email'],
			[['id_prodi'], 'integer']
		];
	}
}

?>

controllers/MahasiswaController.php
<?php  
namespace app\controllers;
use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Mahasiswa;

/**
 * 
 */
class MahasiswaController extends Controller
{
	
	public function actionIndex()
	{
		# code...
		$query = Mahasiswa::find();
		$pagination = new Pagination(['defaultPageSize' => 10,
			'totalCount' => $query->count()]);
		$data_mahasiswa = $query->orderBy('id')
		->offset($pagination->offset)
		->limit($pagination->limit)
		->all();
		return $this->render('index',
			['data_mahasiswa' => $data_mahasiswa,
			'pagination' => $pagination,]);
	}

	public function actionCreate()
	{
		# code...
		$model = new Mahasiswa();

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			# code...
			Yii::$app->session->setFlash('success','Data Berhasil disimpan');
			return $this->refresh();
		}

		return $this->render('create', ['model' => $model,]);
	}

	public function actionUpdate($id)
	{
		# code...
		$model = Mahasiswa::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			# code...
			Yii::$app->session->setFlash('success','Data Berhasil diubah');
			return $this->refresh();
		}
		return $this->render('update',['model' => $model,]);
	}

	public function actionDelete($id)
	{
		# code...
		$model = Mahasiswa::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}
}
?>

views/Mahasiswa/_form.php
<?php  
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Prodi;
?>

<div class="prodi-form">
	<div class="col-md-6">
		<?php $form = ActiveForm::begin(); ?>

		<?= $form->field($model, 'nim')->textInput() ?>
		<?= $form->field($model, 'nama')->textInput() ?>
		<?php $model->isNewRecord==1? $model->jekel='L':$model->jekel; ?>
		<?= $form->field($model, 'jekel')->radioList(array('L'=>'Laki-Laki','P'=>'Perempuan'))->label('Jenis Kelamin') ?>
		<?= $form->field($model, 'id_prodi')->dropDownList(ArrayHelper::map(Prodi::find()->all(),'id','prodi'), ['prompt' => 'Pilih'])->label('Prodi'); ?>
		<?= $form->field($model, 'email')->textInput() ?>
		<?= $form->field($model, 'alamat')->textArea(array('rows'=>4)) ?>
		<div class="form-group">
			<?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
		</div>
		<?php ActiveForm::end(); ?>
	</div>
</div>

views/Mahasiswa/create.php
<h3>Entri Data Mahasiswa</h3>
<?= $this->render('_form', 
		['model' => $model,
	]); 
?>

views/Mahasiswa/index.php
<?php  
use yii\helpers\Html;
use yii\widgets\LinkPager;
?>
<h1>Data Mahasiswa</h1>
<p>
	<?= Html::a('Create Mahasiswa', ['create'], ['class' => 'btn btn-success']) ?>
</p>
<table class="table table-hover">
	<tr>
		<td>ID</td>
		<td>NIM</td>
		<td>Nama</td>
		<td>Jekel</td>
		<td>ID Prodi</td>
		<td>Email</td>
		<td>Alamat</td>
		<td>Aksi</td>
	</tr>
	<?php foreach ($data_mahasiswa as $mahasiswa): ?>
		<tr>
			<td><?= Html::encode($mahasiswa->id)?></td>
			<td><?= Html::encode($mahasiswa->nim)?></td>
			<td><?= Html::encode($mahasiswa->nama)?></td>
			<td><?= Html::encode($mahasiswa->jekel)?></td>
			<td><?= Html::encode($mahasiswa->id_prodi)?></td>
			<td><?= Html::encode($mahasiswa->email)?></td>
			<td><?= Html::encode($mahasiswa->alamat)?></td>
			<td>
				<?= Html::a('Edit', ['mahasiswa/update','id'=>$mahasiswa->id])?> |
				<?= Html::a('Hapus', ['mahasiswa/delete','id'=>$mahasiswa->id],
				['onclick'=>'return(confirm("Yakin Menghapus data ?"))'])?>
			</td>
		</tr>
	<?php endforeach ?>
</table>
<?= LinkPager::widget(['pagination' => $pagination])?>

views/Mahasiswa/update.php
<h3>Edit Data Mahasiswa</h3>
<?= $this->render('_form', ['model' => $model,]) ?>